// Восемь работ: что показываем на главной и на странице проекта.
// Тексты кейсов лежат отдельно, в content/cases/<slug>.md — так их проще править.
export const WORKS = [
  {
    slug: 'widnia',
    title: 'Widnia',
    kind: 'Property developer · catalogue + admin panel',
    lead: 'Every flat shows its price, its price history and its floor plan. Staff run the catalogue themselves; the law says the price history can never be rewritten, so the database makes that impossible.',
    year: '2026',
    tags: ['Catalogue', 'Admin panel', 'Two languages', 'Cloudflare Workers'],
    live: 'https://widnia.oum1d.workers.dev',
    code: 'https://github.com/oum1d/widnia',
    shots: '_en/widnia',
    hero: 'home-en.png',
    gallery: ['catalog-en.png', 'unit-en.png', 'mortgage-en.png', 'home-mobile-en.png'],
    metrics: [['100', 'accessibility'], ['100', 'SEO'], ['94', 'speed']],
  },
  {
    slug: 'roy',
    title: 'Roy',
    kind: 'Science lessons for schoolchildren',
    lead: 'Twenty-four lessons where the phenomenon is not a picture but a running simulation. Move a slider and the swarm, the wave or the crystal behaves differently — the explanation follows what you did.',
    year: '2026',
    tags: ['Simulations', 'Canvas', '32 pages'],
    live: 'https://oum1d.github.io/roy/',
    code: 'https://github.com/oum1d/roy',
    shots: '_en/roy',
    hero: 'lesson.png',
    gallery: ['catalog.png', 'teachers.png', 'pricing.png', 'lesson-mobile.png'],
    metrics: [['24', 'simulations'], ['32', 'pages']],
  },
  {
    slug: 'takt',
    title: 'Takt',
    kind: 'Tram dispatcher system',
    lead: 'A live map where trams move because time moves, not because an animation loops. The dispatcher sees delays build up, opens an incident and watches the line recover.',
    year: '2026',
    tags: ['Live map', 'Dashboard', 'Three languages'],
    live: 'https://oum1d.github.io/takt/',
    code: 'https://github.com/oum1d/takt',
    shots: '_en/takt',
    hero: 'map-en.png',
    gallery: ['home-en.png', 'features-en.png', 'rails-en.png', 'pricing-en.png'],
    metrics: [['3', 'languages']],
  },
  {
    slug: 'zatvor',
    title: 'Zatvor',
    kind: 'Film camera shop',
    lead: 'Every camera is one of a kind, so every camera has its own condition report, its own repair history and its own photographs. When one is sold the page stays — it just says so.',
    year: '2026',
    tags: ['Shop', 'Cart', 'Comparison'],
    live: 'https://oum1d.github.io/zatvor/',
    code: 'https://github.com/oum1d/zatvor',
    shots: '_en/zatvor',
    hero: 'catalog.png',
    gallery: ['camera.png', 'compare.png', 'repair.png', 'camera-mobile.png'],
    metrics: [],
  },
  {
    slug: 'midnight-zone',
    title: 'Midnight Zone',
    kind: 'Deep sea exhibition',
    lead: 'You scroll and you descend. Light drains, pressure rises, the creatures change — the page behaves like the thing it describes.',
    year: '2026',
    tags: ['Scroll narrative', 'Animation'],
    live: 'https://oum1d.github.io/midnight-zone/',
    code: 'https://github.com/oum1d/midnight-zone',
    shots: '_en/midnight',
    hero: 'home-en.png',
    gallery: ['halls-en.png', 'visit-en.png', 'schools-en.png', 'tickets-en.png'],
    metrics: [],
  },
  {
    slug: 'gul',
    title: 'Gul',
    kind: 'Rehearsal rooms · booking',
    lead: 'Four rooms in the basement of an old factory. A band picks a room, a date and an hour, and sees the price before anyone picks up the phone.',
    year: '2026',
    tags: ['Booking', 'Three languages', 'Real photography'],
    live: 'https://oum1d.github.io/gul-rehearsal/',
    code: 'https://github.com/oum1d/gul-rehearsal',
    shots: '_en/gul',
    hero: 'home-en.png',
    gallery: ['rooms-en.png', 'room-en.png', 'pricing-en.png', 'room-mobile-en.png'],
    metrics: [['3', 'languages']],
  },
  {
    slug: 'zarya',
    title: 'Zarya',
    kind: 'Neon sign workshop',
    lead: 'Type your word and the sign is bent in front of you, letter by letter, in a hand-drawn alphabet. The price follows the length of the tube, the way it does in the workshop.',
    year: '2026',
    tags: ['Configurator', 'Custom alphabet', 'SVG'],
    live: 'https://oum1d.github.io/zarya-neon/',
    code: 'https://github.com/oum1d/zarya-neon',
    shots: '_en/zarya',
    hero: 'home-en.png',
    gallery: ['builder-en.png', 'prices-en.png', 'sign-narrow-en.png', 'home-mobile-en.png'],
    metrics: [],
  },
  {
    slug: '30k30',
    title: '30 to 30',
    kind: 'Birthday wishlist',
    lead: 'Thirty gifts for a thirtieth birthday, laid out like a scrapbook. Expensive things can be shared: several people put in what they can and watch the bar fill.',
    year: '2026',
    tags: ['Wishlist', 'Group gifting', 'Scrapbook layout'],
    live: 'https://oum1d.github.io/30k30-wishlist/',
    code: 'https://github.com/oum1d/30k30-wishlist',
    shots: '_en/30k30',
    hero: 'home.png',
    gallery: ['catalog.png', 'pool.png', 'anti.png', 'home-mobile.png'],
    metrics: [['30', 'gifts']],
  },
];
